name: dbt_protectora
version: '1.0.0'
config-version: 2

profile: protectora

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  fecha_inicio_turnos: '2026-04-01'

models:
  dbt_protectora:
    staging:
      +materialized: view
    marts:
      +materialized: table
